# Generated by Django 5.1.7 on 2025-03-21 18:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="posts",
            name="post_image",
            field=models.ImageField(blank=True, null=True, upload_to="post_images"),
        ),
    ]
