# Generated by Django 5.1.7 on 2025-03-24 19:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0003_comment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Comment",
            new_name="Comments",
        ),
    ]
