# Generated by Django 5.1.7 on 2025-03-24 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0004_rename_comment_comments"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="posts",
            name="comments",
        ),
        migrations.AddField(
            model_name="comments",
            name="post",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="posts.posts",
            ),
        ),
    ]
