# Generated by Django 5.1.7 on 2025-04-18 11:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0006_reply"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Reply",
        ),
    ]
