# Generated by Django 5.1.7 on 2025-04-27 16:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0009_alter_reply_replied_to"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posts",
            name="post_image",
            field=models.ImageField(upload_to="post_images"),
        ),
        migrations.AlterField(
            model_name="posts",
            name="text",
            field=models.TextField(max_length=2000),
        ),
    ]
