# Generated by Django 5.0.7 on 2025-05-24 07:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0011_comments_likes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="reply",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="reply_likes", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
