# Generated by Django 5.1.7 on 2025-12-15 23:49

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0012_reply_likes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posts",
            name="post_image",
            field=cloudinary.models.CloudinaryField(
                max_length=255, verbose_name="post_images"
            ),
        ),
    ]
