# Generated by Django 5.0.7 on 2025-04-07 04:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0004_alter_profile_followers_alter_profile_following"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="email",
            field=models.EmailField(blank=True, max_length=200),
        ),
    ]
