# Generated by Django 5.1.7 on 2025-06-16 14:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0006_chats_messages"),
    ]

    operations = [
        migrations.AlterField(
            model_name="messages",
            name="text",
            field=models.CharField(max_length=5000),
        ),
    ]
