# Generated by Django 5.1.7 on 2025-06-17 19:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0007_alter_messages_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="messages",
            name="text",
            field=models.CharField(max_length=2000),
        ),
    ]
