# Generated by Django 5.1.7 on 2025-06-19 10:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0008_alter_messages_text"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="messages",
            options={"ordering": ["created"]},
        ),
        migrations.AddField(
            model_name="chats",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
