# Generated by Django 5.1.7 on 2025-12-15 15:21

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0009_alter_messages_options_chats_updated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_pic",
            field=cloudinary.models.CloudinaryField(
                max_length=255, verbose_name="profile_pic"
            ),
        ),
    ]
