# Generated by Django 5.1.7 on 2025-12-15 18:15

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0011_alter_profile_profile_pic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_pic",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                default="default_cfcdht",
                max_length=255,
                null=True,
                verbose_name="profile_pic",
            ),
        ),
    ]
