# Generated by Django 5.1.7 on 2025-12-15 21:22

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0012_alter_profile_profile_pic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="profile",
            name="first_name",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="profile",
            name="last_name",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="profile",
            name="profile_pic",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="profile_pic"
            ),
        ),
    ]
