# Generated by Django 5.1.7 on 2025-12-15 21:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0013_alter_profile_bio_alter_profile_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="profile",
            name="email",
            field=models.EmailField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="profile",
            name="first_name",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="profile",
            name="last_name",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
