# Generated by Django 5.1.7 on 2025-12-15 23:35

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0015_alter_profile_bio_alter_profile_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_pic",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="profile_pics"
            ),
        ),
    ]
